name: cd dev

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        os: [ubuntu-20.04]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        coverage: xdebug

    - name: Validate Composer
      run: composer validate --strict

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Serverless
      run: npm install -g serverless

    - name: Install Serverless Stack Output
      run: npm install -g serverless-stack-output

    - name: Install JQ
      run: apt-get install -y jq
