name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        os: [ubuntu-20.04]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        coverage: xdebug

    - name: Validate Composer
      run: composer validate

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run Static Analysis
      run: composer run-script pipeline
